### ISSUE TITLE
完成はいいものの Heroku にデプロイできない...

### ISSUE THREAD

**Issue by yum45f** [yu-san-19/redirect-next-event#1]
完成はいいものの、 Heroku にデプロイができない。
おそらく Gemfile 関連だとは思う。

Travis CI も

## さっと調べた原因一覧（後日ゆっくり解消）

- SQLite 3 (Gem)
- pd (Gem)

以下コメントで追記

**Comment by yum45f** [comment]
Cloud9 IDE が 謎のリダイレクト多発で弾かれた。
環境自体が壊れているかも。

**Comment by yu-san-19** [comment]
別環境の Rails Sever でError Name or service not known (SocketError)

**Comment by yum45f** [comment]
Gemfile.lock 辺りも怪しい。
やはり、Heroku は SQLite 3には対応しておらず、別のDBを使っているので、そのためのGemを入れる必要があるみたい。

**Comment by yum45f** [comment]
```
Specified 'postgresql' for database adapter, but the gem is not loaded. Add `gem 'pg'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord). (Gem::LoadError)
```
pg はインストールされているはず。

**Comment by yum45f** [comment]
もう一回、Rails チュートリアルにある通りに新規環境に書き直したらCIもPassed で無事動作確認。
おそらく　pg を production 環境に指定していた方がよかったってことかも。
それは時間がある時に検証するとして取り合えず Closed。
